# Makefile for structure_example.c

# Compiler
CC = gcc

# Target executable
TARGET = structure_example

# Source file
SRC = structure_example.c

# Compilation rule
$(TARGET): $(SRC)
	$(CC) $(SRC) -o $(TARGET)

# Clean rule
clean:
	del $(TARGET).exe
